/**
 * @fileoverview gRPC-Web generated client stub for jobmanagement
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.28.2
// source: job_management.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as job_management_pb from './job_management_pb'; // proto import: "job_management.proto"


export class JobServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorListAllJobs = new grpcWeb.MethodDescriptor(
    '/jobmanagement.JobService/ListAllJobs',
    grpcWeb.MethodType.UNARY,
    job_management_pb.Empty,
    job_management_pb.JobList,
    (request: job_management_pb.Empty) => {
      return request.serializeBinary();
    },
    job_management_pb.JobList.deserializeBinary
  );

  listAllJobs(
    request: job_management_pb.Empty,
    metadata?: grpcWeb.Metadata | null): Promise<job_management_pb.JobList>;

  listAllJobs(
    request: job_management_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: job_management_pb.JobList) => void): grpcWeb.ClientReadableStream<job_management_pb.JobList>;

  listAllJobs(
    request: job_management_pb.Empty,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: job_management_pb.JobList) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/jobmanagement.JobService/ListAllJobs',
        request,
        metadata || {},
        this.methodDescriptorListAllJobs,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/jobmanagement.JobService/ListAllJobs',
    request,
    metadata || {},
    this.methodDescriptorListAllJobs);
  }

  methodDescriptorGetJobDetails = new grpcWeb.MethodDescriptor(
    '/jobmanagement.JobService/GetJobDetails',
    grpcWeb.MethodType.UNARY,
    job_management_pb.JobId,
    job_management_pb.JobDetails,
    (request: job_management_pb.JobId) => {
      return request.serializeBinary();
    },
    job_management_pb.JobDetails.deserializeBinary
  );

  getJobDetails(
    request: job_management_pb.JobId,
    metadata?: grpcWeb.Metadata | null): Promise<job_management_pb.JobDetails>;

  getJobDetails(
    request: job_management_pb.JobId,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: job_management_pb.JobDetails) => void): grpcWeb.ClientReadableStream<job_management_pb.JobDetails>;

  getJobDetails(
    request: job_management_pb.JobId,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: job_management_pb.JobDetails) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/jobmanagement.JobService/GetJobDetails',
        request,
        metadata || {},
        this.methodDescriptorGetJobDetails,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/jobmanagement.JobService/GetJobDetails',
    request,
    metadata || {},
    this.methodDescriptorGetJobDetails);
  }

}

